language: generic

services:
  - docker

before_install:
  - sudo service postgresql stop
  - (cd /opt; curl https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/4.2.0/flyway-commandline-4.2.0-linux-x64.tar.gz | tar xzf -)
  - export PATH=$PATH:/opt/flyway-4.2.0

script:
  - make test && docker login -u mrrusof -p $DOCKER_PWD && make push
