version: "3.2"

services:

  the-official-journal:
    build: .
    image: mrrusof/the-official-journal
    ports:
      - 3000:3000
    links:
      - the-law
  
  the-law:
    image: mrrusof/the-law
    ports:
      - 5432:5432
